# Generated by Django 4.0.5 on 2022-10-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='gc',
        ),
        migrations.RemoveField(
            model_name='message',
            name='student',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
